// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: api/diff-api.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EntrypointType int32

const (
	EntrypointType_KUBERNETES EntrypointType = 0
)

// Enum value maps for EntrypointType.
var (
	EntrypointType_name = map[int32]string{
		0: "KUBERNETES",
	}
	EntrypointType_value = map[string]int32{
		"KUBERNETES": 0,
	}
)

func (x EntrypointType) Enum() *EntrypointType {
	p := new(EntrypointType)
	*p = x
	return p
}

func (x EntrypointType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EntrypointType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_diff_api_proto_enumTypes[0].Descriptor()
}

func (EntrypointType) Type() protoreflect.EnumType {
	return &file_api_diff_api_proto_enumTypes[0]
}

func (x EntrypointType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EntrypointType.Descriptor instead.
func (EntrypointType) EnumDescriptor() ([]byte, []int) {
	return file_api_diff_api_proto_rawDescGZIP(), []int{0}
}

type DiffType int32

const (
	DiffType_CREATE DiffType = 0
	DiffType_UPDATE DiffType = 1
	DiffType_DELETE DiffType = 2
)

// Enum value maps for DiffType.
var (
	DiffType_name = map[int32]string{
		0: "CREATE",
		1: "UPDATE",
		2: "DELETE",
	}
	DiffType_value = map[string]int32{
		"CREATE": 0,
		"UPDATE": 1,
		"DELETE": 2,
	}
)

func (x DiffType) Enum() *DiffType {
	p := new(DiffType)
	*p = x
	return p
}

func (x DiffType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (DiffType) Descriptor() protoreflect.EnumDescriptor {
	return file_api_diff_api_proto_enumTypes[1].Descriptor()
}

func (DiffType) Type() protoreflect.EnumType {
	return &file_api_diff_api_proto_enumTypes[1]
}

func (x DiffType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use DiffType.Descriptor instead.
func (DiffType) EnumDescriptor() ([]byte, []int) {
	return file_api_diff_api_proto_rawDescGZIP(), []int{1}
}

type DiffRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	From    *Reference          `protobuf:"bytes,1,opt,name=From,proto3" json:"From,omitempty"`
	To      *Reference          `protobuf:"bytes,2,opt,name=To,proto3" json:"To,omitempty"`
	Filters *DiffRequest_Filter `protobuf:"bytes,3,opt,name=Filters,proto3" json:"Filters,omitempty"`
}

func (x *DiffRequest) Reset() {
	*x = DiffRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_diff_api_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiffRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffRequest) ProtoMessage() {}

func (x *DiffRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_diff_api_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffRequest.ProtoReflect.Descriptor instead.
func (*DiffRequest) Descriptor() ([]byte, []int) {
	return file_api_diff_api_proto_rawDescGZIP(), []int{0}
}

func (x *DiffRequest) GetFrom() *Reference {
	if x != nil {
		return x.From
	}
	return nil
}

func (x *DiffRequest) GetTo() *Reference {
	if x != nil {
		return x.To
	}
	return nil
}

func (x *DiffRequest) GetFilters() *DiffRequest_Filter {
	if x != nil {
		return x.Filters
	}
	return nil
}

type Reference struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Repository *Repository `protobuf:"bytes,1,opt,name=Repository,proto3" json:"Repository,omitempty"`
	Target     string      `protobuf:"bytes,2,opt,name=Target,proto3" json:"Target,omitempty"`
}

func (x *Reference) Reset() {
	*x = Reference{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_diff_api_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Reference) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Reference) ProtoMessage() {}

func (x *Reference) ProtoReflect() protoreflect.Message {
	mi := &file_api_diff_api_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Reference.ProtoReflect.Descriptor instead.
func (*Reference) Descriptor() ([]byte, []int) {
	return file_api_diff_api_proto_rawDescGZIP(), []int{1}
}

func (x *Reference) GetRepository() *Repository {
	if x != nil {
		return x.Repository
	}
	return nil
}

func (x *Reference) GetTarget() string {
	if x != nil {
		return x.Target
	}
	return ""
}

type Entrypoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name      string            `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Directory string            `protobuf:"bytes,2,opt,name=Directory,proto3" json:"Directory,omitempty"`
	Type      EntrypointType    `protobuf:"varint,3,opt,name=Type,proto3,enum=apipb.EntrypointType" json:"Type,omitempty"`
	Context   map[string]string `protobuf:"bytes,4,rep,name=Context,proto3" json:"Context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *Entrypoint) Reset() {
	*x = Entrypoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_diff_api_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Entrypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Entrypoint) ProtoMessage() {}

func (x *Entrypoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_diff_api_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Entrypoint.ProtoReflect.Descriptor instead.
func (*Entrypoint) Descriptor() ([]byte, []int) {
	return file_api_diff_api_proto_rawDescGZIP(), []int{2}
}

func (x *Entrypoint) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Entrypoint) GetDirectory() string {
	if x != nil {
		return x.Directory
	}
	return ""
}

func (x *Entrypoint) GetType() EntrypointType {
	if x != nil {
		return x.Type
	}
	return EntrypointType_KUBERNETES
}

func (x *Entrypoint) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type Resource struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Resource) Reset() {
	*x = Resource{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_diff_api_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_api_diff_api_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_api_diff_api_proto_rawDescGZIP(), []int{3}
}

type DiffResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Diffs []*DiffResponse_Diff `protobuf:"bytes,1,rep,name=Diffs,proto3" json:"Diffs,omitempty"`
	Error string               `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
}

func (x *DiffResponse) Reset() {
	*x = DiffResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_diff_api_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiffResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffResponse) ProtoMessage() {}

func (x *DiffResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_diff_api_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffResponse.ProtoReflect.Descriptor instead.
func (*DiffResponse) Descriptor() ([]byte, []int) {
	return file_api_diff_api_proto_rawDescGZIP(), []int{4}
}

func (x *DiffResponse) GetDiffs() []*DiffResponse_Diff {
	if x != nil {
		return x.Diffs
	}
	return nil
}

func (x *DiffResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type DiffRequest_EntrypointList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entrypoints []*Entrypoint `protobuf:"bytes,1,rep,name=Entrypoints,proto3" json:"Entrypoints,omitempty"`
}

func (x *DiffRequest_EntrypointList) Reset() {
	*x = DiffRequest_EntrypointList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_diff_api_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiffRequest_EntrypointList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffRequest_EntrypointList) ProtoMessage() {}

func (x *DiffRequest_EntrypointList) ProtoReflect() protoreflect.Message {
	mi := &file_api_diff_api_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffRequest_EntrypointList.ProtoReflect.Descriptor instead.
func (*DiffRequest_EntrypointList) Descriptor() ([]byte, []int) {
	return file_api_diff_api_proto_rawDescGZIP(), []int{0, 0}
}

func (x *DiffRequest_EntrypointList) GetEntrypoints() []*Entrypoint {
	if x != nil {
		return x.Entrypoints
	}
	return nil
}

type DiffRequest_AutomatedEntrypoint struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Types   []EntrypointType  `protobuf:"varint,1,rep,packed,name=Types,proto3,enum=apipb.EntrypointType" json:"Types,omitempty"`
	Context map[string]string `protobuf:"bytes,2,rep,name=Context,proto3" json:"Context,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *DiffRequest_AutomatedEntrypoint) Reset() {
	*x = DiffRequest_AutomatedEntrypoint{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_diff_api_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiffRequest_AutomatedEntrypoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffRequest_AutomatedEntrypoint) ProtoMessage() {}

func (x *DiffRequest_AutomatedEntrypoint) ProtoReflect() protoreflect.Message {
	mi := &file_api_diff_api_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffRequest_AutomatedEntrypoint.ProtoReflect.Descriptor instead.
func (*DiffRequest_AutomatedEntrypoint) Descriptor() ([]byte, []int) {
	return file_api_diff_api_proto_rawDescGZIP(), []int{0, 1}
}

func (x *DiffRequest_AutomatedEntrypoint) GetTypes() []EntrypointType {
	if x != nil {
		return x.Types
	}
	return nil
}

func (x *DiffRequest_AutomatedEntrypoint) GetContext() map[string]string {
	if x != nil {
		return x.Context
	}
	return nil
}

type DiffRequest_Filter struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Filter:
	//
	//	*DiffRequest_Filter_Entrypoints
	//	*DiffRequest_Filter_AutomatedEntrypoint
	Filter isDiffRequest_Filter_Filter `protobuf_oneof:"Filter"`
}

func (x *DiffRequest_Filter) Reset() {
	*x = DiffRequest_Filter{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_diff_api_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiffRequest_Filter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffRequest_Filter) ProtoMessage() {}

func (x *DiffRequest_Filter) ProtoReflect() protoreflect.Message {
	mi := &file_api_diff_api_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffRequest_Filter.ProtoReflect.Descriptor instead.
func (*DiffRequest_Filter) Descriptor() ([]byte, []int) {
	return file_api_diff_api_proto_rawDescGZIP(), []int{0, 2}
}

func (m *DiffRequest_Filter) GetFilter() isDiffRequest_Filter_Filter {
	if m != nil {
		return m.Filter
	}
	return nil
}

func (x *DiffRequest_Filter) GetEntrypoints() *DiffRequest_EntrypointList {
	if x, ok := x.GetFilter().(*DiffRequest_Filter_Entrypoints); ok {
		return x.Entrypoints
	}
	return nil
}

func (x *DiffRequest_Filter) GetAutomatedEntrypoint() *DiffRequest_AutomatedEntrypoint {
	if x, ok := x.GetFilter().(*DiffRequest_Filter_AutomatedEntrypoint); ok {
		return x.AutomatedEntrypoint
	}
	return nil
}

type isDiffRequest_Filter_Filter interface {
	isDiffRequest_Filter_Filter()
}

type DiffRequest_Filter_Entrypoints struct {
	Entrypoints *DiffRequest_EntrypointList `protobuf:"bytes,1,opt,name=Entrypoints,proto3,oneof"`
}

type DiffRequest_Filter_AutomatedEntrypoint struct {
	AutomatedEntrypoint *DiffRequest_AutomatedEntrypoint `protobuf:"bytes,2,opt,name=AutomatedEntrypoint,proto3,oneof"`
}

func (*DiffRequest_Filter_Entrypoints) isDiffRequest_Filter_Filter() {}

func (*DiffRequest_Filter_AutomatedEntrypoint) isDiffRequest_Filter_Filter() {}

type DiffResponse_Diff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entrypoint *Entrypoint                         `protobuf:"bytes,1,opt,name=Entrypoint,proto3" json:"Entrypoint,omitempty"`
	Error      string                              `protobuf:"bytes,2,opt,name=Error,proto3" json:"Error,omitempty"`
	Changes    []*DiffResponse_Diff_EntrypointDiff `protobuf:"bytes,3,rep,name=Changes,proto3" json:"Changes,omitempty"`
}

func (x *DiffResponse_Diff) Reset() {
	*x = DiffResponse_Diff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_diff_api_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiffResponse_Diff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffResponse_Diff) ProtoMessage() {}

func (x *DiffResponse_Diff) ProtoReflect() protoreflect.Message {
	mi := &file_api_diff_api_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffResponse_Diff.ProtoReflect.Descriptor instead.
func (*DiffResponse_Diff) Descriptor() ([]byte, []int) {
	return file_api_diff_api_proto_rawDescGZIP(), []int{4, 0}
}

func (x *DiffResponse_Diff) GetEntrypoint() *Entrypoint {
	if x != nil {
		return x.Entrypoint
	}
	return nil
}

func (x *DiffResponse_Diff) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *DiffResponse_Diff) GetChanges() []*DiffResponse_Diff_EntrypointDiff {
	if x != nil {
		return x.Changes
	}
	return nil
}

type DiffResponse_Diff_EntrypointDiff struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type  DiffType                                   `protobuf:"varint,1,opt,name=Type,proto3,enum=apipb.DiffType" json:"Type,omitempty"`
	Pre   *Resource                                  `protobuf:"bytes,2,opt,name=Pre,proto3" json:"Pre,omitempty"`
	Post  *Resource                                  `protobuf:"bytes,3,opt,name=Post,proto3" json:"Post,omitempty"`
	Diffs []*DiffResponse_Diff_EntrypointDiff_Change `protobuf:"bytes,4,rep,name=Diffs,proto3" json:"Diffs,omitempty"`
}

func (x *DiffResponse_Diff_EntrypointDiff) Reset() {
	*x = DiffResponse_Diff_EntrypointDiff{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_diff_api_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiffResponse_Diff_EntrypointDiff) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffResponse_Diff_EntrypointDiff) ProtoMessage() {}

func (x *DiffResponse_Diff_EntrypointDiff) ProtoReflect() protoreflect.Message {
	mi := &file_api_diff_api_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffResponse_Diff_EntrypointDiff.ProtoReflect.Descriptor instead.
func (*DiffResponse_Diff_EntrypointDiff) Descriptor() ([]byte, []int) {
	return file_api_diff_api_proto_rawDescGZIP(), []int{4, 0, 0}
}

func (x *DiffResponse_Diff_EntrypointDiff) GetType() DiffType {
	if x != nil {
		return x.Type
	}
	return DiffType_CREATE
}

func (x *DiffResponse_Diff_EntrypointDiff) GetPre() *Resource {
	if x != nil {
		return x.Pre
	}
	return nil
}

func (x *DiffResponse_Diff_EntrypointDiff) GetPost() *Resource {
	if x != nil {
		return x.Post
	}
	return nil
}

func (x *DiffResponse_Diff_EntrypointDiff) GetDiffs() []*DiffResponse_Diff_EntrypointDiff_Change {
	if x != nil {
		return x.Diffs
	}
	return nil
}

type DiffResponse_Diff_EntrypointDiff_Change struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Type   string   `protobuf:"bytes,1,opt,name=Type,proto3" json:"Type,omitempty"`
	Path   []string `protobuf:"bytes,2,rep,name=Path,proto3" json:"Path,omitempty"`
	From   string   `protobuf:"bytes,3,opt,name=From,proto3" json:"From,omitempty"`
	To     string   `protobuf:"bytes,4,opt,name=To,proto3" json:"To,omitempty"`
	Parent string   `protobuf:"bytes,5,opt,name=parent,proto3" json:"parent,omitempty"`
}

func (x *DiffResponse_Diff_EntrypointDiff_Change) Reset() {
	*x = DiffResponse_Diff_EntrypointDiff_Change{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_diff_api_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DiffResponse_Diff_EntrypointDiff_Change) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DiffResponse_Diff_EntrypointDiff_Change) ProtoMessage() {}

func (x *DiffResponse_Diff_EntrypointDiff_Change) ProtoReflect() protoreflect.Message {
	mi := &file_api_diff_api_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DiffResponse_Diff_EntrypointDiff_Change.ProtoReflect.Descriptor instead.
func (*DiffResponse_Diff_EntrypointDiff_Change) Descriptor() ([]byte, []int) {
	return file_api_diff_api_proto_rawDescGZIP(), []int{4, 0, 0, 0}
}

func (x *DiffResponse_Diff_EntrypointDiff_Change) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *DiffResponse_Diff_EntrypointDiff_Change) GetPath() []string {
	if x != nil {
		return x.Path
	}
	return nil
}

func (x *DiffResponse_Diff_EntrypointDiff_Change) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *DiffResponse_Diff_EntrypointDiff_Change) GetTo() string {
	if x != nil {
		return x.To
	}
	return ""
}

func (x *DiffResponse_Diff_EntrypointDiff_Change) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

var File_api_diff_api_proto protoreflect.FileDescriptor

var file_api_diff_api_proto_rawDesc = []byte{
	0x0a, 0x12, 0x61, 0x70, 0x69, 0x2f, 0x64, 0x69, 0x66, 0x66, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x61, 0x70, 0x69, 0x70, 0x62, 0x1a, 0x12, 0x61, 0x70, 0x69,
	0x2f, 0x72, 0x65, 0x70, 0x6f, 0x2d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xd9, 0x04, 0x0a, 0x0b, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x24, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e,
	0x61, 0x70, 0x69, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x52,
	0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x20, 0x0a, 0x02, 0x54, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x10, 0x2e, 0x61, 0x70, 0x69, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x66, 0x65, 0x72, 0x65,
	0x6e, 0x63, 0x65, 0x52, 0x02, 0x54, 0x6f, 0x12, 0x33, 0x0a, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65,
	0x72, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69, 0x70, 0x62,
	0x2e, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x46, 0x69, 0x6c,
	0x74, 0x65, 0x72, 0x52, 0x07, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x73, 0x1a, 0x45, 0x0a, 0x0e,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x33,
	0x0a, 0x0b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x74, 0x72,
	0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x73, 0x1a, 0xcd, 0x01, 0x0a, 0x13, 0x41, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x65,
	0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x12, 0x2b, 0x0a, 0x05, 0x54,
	0x79, 0x70, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0e, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69,
	0x70, 0x62, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x54, 0x79, 0x70,
	0x65, 0x52, 0x05, 0x54, 0x79, 0x70, 0x65, 0x73, 0x12, 0x4d, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74,
	0x65, 0x78, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x33, 0x2e, 0x61, 0x70, 0x69, 0x70,
	0x62, 0x2e, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x75,
	0x74, 0x6f, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07,
	0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x1a, 0x3a, 0x0a, 0x0c, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x78, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a,
	0x02, 0x38, 0x01, 0x1a, 0xb5, 0x01, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x12, 0x45,
	0x0a, 0x0b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x66, 0x66,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0b, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x73, 0x12, 0x5a, 0x0a, 0x13, 0x41, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74,
	0x65, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x26, 0x2e, 0x61, 0x70, 0x69, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x66, 0x66, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x41, 0x75, 0x74, 0x6f, 0x6d, 0x61, 0x74, 0x65, 0x64,
	0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x13, 0x41, 0x75,
	0x74, 0x6f, 0x6d, 0x61, 0x74, 0x65, 0x64, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x42, 0x08, 0x0a, 0x06, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x56, 0x0a, 0x09, 0x52,
	0x65, 0x66, 0x65, 0x72, 0x65, 0x6e, 0x63, 0x65, 0x12, 0x31, 0x0a, 0x0a, 0x52, 0x65, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61,
	0x70, 0x69, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x52,
	0x0a, 0x52, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x6f, 0x72, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x54,
	0x61, 0x72, 0x67, 0x65, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x54, 0x61, 0x72,
	0x67, 0x65, 0x74, 0x22, 0xdf, 0x01, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69,
	0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63, 0x74,
	0x6f, 0x72, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x44, 0x69, 0x72, 0x65, 0x63,
	0x74, 0x6f, 0x72, 0x79, 0x12, 0x29, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0e, 0x32, 0x15, 0x2e, 0x61, 0x70, 0x69, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x70, 0x6f, 0x69, 0x6e, 0x74, 0x54, 0x79, 0x70, 0x65, 0x52, 0x04, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x38, 0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x70, 0x62, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f,
	0x69, 0x6e, 0x74, 0x2e, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79,
	0x52, 0x07, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x78, 0x74, 0x1a, 0x3a, 0x0a, 0x0c, 0x43, 0x6f, 0x6e,
	0x74, 0x65, 0x78, 0x74, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12, 0x14, 0x0a, 0x05, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75,
	0x65, 0x3a, 0x02, 0x38, 0x01, 0x22, 0x0a, 0x0a, 0x08, 0x52, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63,
	0x65, 0x22, 0x9d, 0x04, 0x0a, 0x0c, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x12, 0x2e, 0x0a, 0x05, 0x44, 0x69, 0x66, 0x66, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x18, 0x2e, 0x61, 0x70, 0x69, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2e, 0x44, 0x69, 0x66, 0x66, 0x52, 0x05, 0x44, 0x69, 0x66,
	0x66, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x1a, 0xc6, 0x03, 0x0a, 0x04, 0x44, 0x69, 0x66,
	0x66, 0x12, 0x31, 0x0a, 0x0a, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x61, 0x70, 0x69, 0x70, 0x62, 0x2e, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x52, 0x0a, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70,
	0x6f, 0x69, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x41, 0x0a, 0x07, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27, 0x2e, 0x61, 0x70,
	0x69, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x2e, 0x44, 0x69, 0x66, 0x66, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74,
	0x44, 0x69, 0x66, 0x66, 0x52, 0x07, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x73, 0x1a, 0xb1, 0x02,
	0x0a, 0x0e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x44, 0x69, 0x66, 0x66,
	0x12, 0x23, 0x0a, 0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x0f,
	0x2e, 0x61, 0x70, 0x69, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x66, 0x66, 0x54, 0x79, 0x70, 0x65, 0x52,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x12, 0x21, 0x0a, 0x03, 0x50, 0x72, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x70, 0x62, 0x2e, 0x52, 0x65, 0x73, 0x6f, 0x75,
	0x72, 0x63, 0x65, 0x52, 0x03, 0x50, 0x72, 0x65, 0x12, 0x23, 0x0a, 0x04, 0x50, 0x6f, 0x73, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0f, 0x2e, 0x61, 0x70, 0x69, 0x70, 0x62, 0x2e, 0x52,
	0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x52, 0x04, 0x50, 0x6f, 0x73, 0x74, 0x12, 0x44, 0x0a,
	0x05, 0x44, 0x69, 0x66, 0x66, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x2e, 0x2e, 0x61,
	0x70, 0x69, 0x70, 0x62, 0x2e, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x2e, 0x44, 0x69, 0x66, 0x66, 0x2e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e,
	0x74, 0x44, 0x69, 0x66, 0x66, 0x2e, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x52, 0x05, 0x44, 0x69,
	0x66, 0x66, 0x73, 0x1a, 0x6c, 0x0a, 0x06, 0x43, 0x68, 0x61, 0x6e, 0x67, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x12, 0x0a, 0x04, 0x50, 0x61, 0x74, 0x68, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x04, 0x50, 0x61, 0x74, 0x68, 0x12, 0x12, 0x0a, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x04, 0x46, 0x72, 0x6f, 0x6d, 0x12, 0x0e, 0x0a, 0x02, 0x54, 0x6f, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x54, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x70, 0x61, 0x72,
	0x65, 0x6e, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x61, 0x72, 0x65, 0x6e,
	0x74, 0x2a, 0x20, 0x0a, 0x0e, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x70, 0x6f, 0x69, 0x6e, 0x74, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x0e, 0x0a, 0x0a, 0x4b, 0x55, 0x42, 0x45, 0x52, 0x4e, 0x45, 0x54, 0x45,
	0x53, 0x10, 0x00, 0x2a, 0x2e, 0x0a, 0x08, 0x44, 0x69, 0x66, 0x66, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x0a, 0x0a, 0x06, 0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x00, 0x12, 0x0a, 0x0a, 0x06, 0x55,
	0x50, 0x44, 0x41, 0x54, 0x45, 0x10, 0x01, 0x12, 0x0a, 0x0a, 0x06, 0x44, 0x45, 0x4c, 0x45, 0x54,
	0x45, 0x10, 0x02, 0x32, 0x3a, 0x0a, 0x07, 0x44, 0x69, 0x66, 0x66, 0x41, 0x70, 0x69, 0x12, 0x2f,
	0x0a, 0x04, 0x44, 0x69, 0x66, 0x66, 0x12, 0x12, 0x2e, 0x61, 0x70, 0x69, 0x70, 0x62, 0x2e, 0x44,
	0x69, 0x66, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x13, 0x2e, 0x61, 0x70, 0x69,
	0x70, 0x62, 0x2e, 0x44, 0x69, 0x66, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42,
	0x2c, 0x5a, 0x2a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x63, 0x6f,
	0x64, 0x69, 0x6e, 0x67, 0x6e, 0x69, 0x6e, 0x6a, 0x61, 0x2f, 0x67, 0x69, 0x74, 0x6f, 0x70, 0x73,
	0x2d, 0x72, 0x65, 0x70, 0x6f, 0x2d, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_diff_api_proto_rawDescOnce sync.Once
	file_api_diff_api_proto_rawDescData = file_api_diff_api_proto_rawDesc
)

func file_api_diff_api_proto_rawDescGZIP() []byte {
	file_api_diff_api_proto_rawDescOnce.Do(func() {
		file_api_diff_api_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_diff_api_proto_rawDescData)
	})
	return file_api_diff_api_proto_rawDescData
}

var file_api_diff_api_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_api_diff_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_api_diff_api_proto_goTypes = []interface{}{
	(EntrypointType)(0),                      // 0: apipb.EntrypointType
	(DiffType)(0),                            // 1: apipb.DiffType
	(*DiffRequest)(nil),                      // 2: apipb.DiffRequest
	(*Reference)(nil),                        // 3: apipb.Reference
	(*Entrypoint)(nil),                       // 4: apipb.Entrypoint
	(*Resource)(nil),                         // 5: apipb.Resource
	(*DiffResponse)(nil),                     // 6: apipb.DiffResponse
	(*DiffRequest_EntrypointList)(nil),       // 7: apipb.DiffRequest.EntrypointList
	(*DiffRequest_AutomatedEntrypoint)(nil),  // 8: apipb.DiffRequest.AutomatedEntrypoint
	(*DiffRequest_Filter)(nil),               // 9: apipb.DiffRequest.Filter
	nil,                                      // 10: apipb.DiffRequest.AutomatedEntrypoint.ContextEntry
	nil,                                      // 11: apipb.Entrypoint.ContextEntry
	(*DiffResponse_Diff)(nil),                // 12: apipb.DiffResponse.Diff
	(*DiffResponse_Diff_EntrypointDiff)(nil), // 13: apipb.DiffResponse.Diff.EntrypointDiff
	(*DiffResponse_Diff_EntrypointDiff_Change)(nil), // 14: apipb.DiffResponse.Diff.EntrypointDiff.Change
	(*Repository)(nil), // 15: apipb.Repository
}
var file_api_diff_api_proto_depIdxs = []int32{
	3,  // 0: apipb.DiffRequest.From:type_name -> apipb.Reference
	3,  // 1: apipb.DiffRequest.To:type_name -> apipb.Reference
	9,  // 2: apipb.DiffRequest.Filters:type_name -> apipb.DiffRequest.Filter
	15, // 3: apipb.Reference.Repository:type_name -> apipb.Repository
	0,  // 4: apipb.Entrypoint.Type:type_name -> apipb.EntrypointType
	11, // 5: apipb.Entrypoint.Context:type_name -> apipb.Entrypoint.ContextEntry
	12, // 6: apipb.DiffResponse.Diffs:type_name -> apipb.DiffResponse.Diff
	4,  // 7: apipb.DiffRequest.EntrypointList.Entrypoints:type_name -> apipb.Entrypoint
	0,  // 8: apipb.DiffRequest.AutomatedEntrypoint.Types:type_name -> apipb.EntrypointType
	10, // 9: apipb.DiffRequest.AutomatedEntrypoint.Context:type_name -> apipb.DiffRequest.AutomatedEntrypoint.ContextEntry
	7,  // 10: apipb.DiffRequest.Filter.Entrypoints:type_name -> apipb.DiffRequest.EntrypointList
	8,  // 11: apipb.DiffRequest.Filter.AutomatedEntrypoint:type_name -> apipb.DiffRequest.AutomatedEntrypoint
	4,  // 12: apipb.DiffResponse.Diff.Entrypoint:type_name -> apipb.Entrypoint
	13, // 13: apipb.DiffResponse.Diff.Changes:type_name -> apipb.DiffResponse.Diff.EntrypointDiff
	1,  // 14: apipb.DiffResponse.Diff.EntrypointDiff.Type:type_name -> apipb.DiffType
	5,  // 15: apipb.DiffResponse.Diff.EntrypointDiff.Pre:type_name -> apipb.Resource
	5,  // 16: apipb.DiffResponse.Diff.EntrypointDiff.Post:type_name -> apipb.Resource
	14, // 17: apipb.DiffResponse.Diff.EntrypointDiff.Diffs:type_name -> apipb.DiffResponse.Diff.EntrypointDiff.Change
	2,  // 18: apipb.DiffApi.Diff:input_type -> apipb.DiffRequest
	6,  // 19: apipb.DiffApi.Diff:output_type -> apipb.DiffResponse
	19, // [19:20] is the sub-list for method output_type
	18, // [18:19] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_api_diff_api_proto_init() }
func file_api_diff_api_proto_init() {
	if File_api_diff_api_proto != nil {
		return
	}
	file_api_repo_api_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_api_diff_api_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiffRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_diff_api_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Reference); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_diff_api_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Entrypoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_diff_api_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Resource); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_diff_api_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiffResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_diff_api_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiffRequest_EntrypointList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_diff_api_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiffRequest_AutomatedEntrypoint); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_diff_api_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiffRequest_Filter); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_diff_api_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiffResponse_Diff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_diff_api_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiffResponse_Diff_EntrypointDiff); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_diff_api_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DiffResponse_Diff_EntrypointDiff_Change); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_api_diff_api_proto_msgTypes[7].OneofWrappers = []interface{}{
		(*DiffRequest_Filter_Entrypoints)(nil),
		(*DiffRequest_Filter_AutomatedEntrypoint)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_diff_api_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_diff_api_proto_goTypes,
		DependencyIndexes: file_api_diff_api_proto_depIdxs,
		EnumInfos:         file_api_diff_api_proto_enumTypes,
		MessageInfos:      file_api_diff_api_proto_msgTypes,
	}.Build()
	File_api_diff_api_proto = out.File
	file_api_diff_api_proto_rawDesc = nil
	file_api_diff_api_proto_goTypes = nil
	file_api_diff_api_proto_depIdxs = nil
}
